title: "Asoba API Documentation"
description: "Energy-as-a-Service API documentation"
remote_theme: "just-the-docs/just-the-docs"

just_the_docs:
  show_toc: true         # Enable the table of contents sidebar
  toc_level: 2           # Show headers starting from ## in the ToC
