# Minimal Mistakes Jekyll Theme Configuration
title: "Asoba API Documentation"
description: "Documentation for Asoba's Energy platform"
remote_theme: "mmistakes/minimal-mistakes"
theme: "minimal-mistakes"

# Enable navigation and sidebar options
plugins:
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-sitemap

# Enable table of contents
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      toc: true            # Enable table of contents
      toc_sticky: true      # Keep ToC visible
      sidebar: true         # Enable sidebar

# Configure navigation
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Documentation"
      url: "/docs/"
