title: "Asoba API Documentation"
description: "Energy-as-a-Service API documentation"
remote_theme: "just-the-docs/just-the-docs"

# Set base URL if using a subfolder
baseurl: "/"

sass:
  load_paths:
    - assets/css
