title: "Asoba API Documentation"
description: "Energy-as-a-Service API documentation"
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
sass:
  load_paths:
    - assets/css
