title: "Asoba API Documentation"
description: "Energy-as-a-Service API documentation"
remote_theme: just-the-docs/just-the-docs

# Configure table of contents
just_the_docs:
  show_toc: true           # Enable table of contents in sidebar
  toc_level: 2             # Start at ## headers
  search_enabled: true     # Enable search functionality
